[package]
name = "lqr-mania"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = {version = "0.30", default-features = false, features = ["libm", "alloc"]}
rand_core = "0.6.4"

[dev-dependencies]
rand_core = {version = "0.6.4", features = ["getrandom"]}